version: '3'
services:
  hk-nginx:
    container_name: hk-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: store
      MYSQL_ROOT_PASSWORD: Aa@123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    restart: always
    build: ./app-web
    working_dir: /app
    volumes:
      - ./app-web:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    ports:
      - "8082:8082"
    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql