spring:
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ${database.user}
    password: ${database.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        type: trace
        show-sql: true
        proc:
          param_null_passing: true
  flyway:
    enabled: false
  thymeleaf:
    cache: false
  mustache:
    cache: false
  groovy:
    template:
      cache: false

  devtools:
    restart:
      exclude: static/**,templates/**
server:
  port: 8082
  servlet:
    session:
      timeout: 60m
paypal:
  mode: sandbox
  client:
    app: AfWb_YBTZwt9J37nCed5XRMuJ29CTAHoOKG6iqtWGL7Yit4RdVi30XQw-ZDswmynnGSp8kvFYBqN9JKA
    secret: EE8-9h5ewxUO1ZXgLIRIZ5_GrFSzVvFHjeplMWsJnBuboarsTEu5pMYEXFarls586ZjjUHqULJXzRI9L